# substitutions:
#   _FOLDER: "005__build-workflows"

steps:
- name: 'ubuntu'
  args: ["ls", "${FOLDER}"]
  # args: ["echo","005__build-workflows"]
  # args: ["ls","005__build-workflows"]
    # - "-c"
    # # - "ls $$FOLDER"
    # - 


# # create dataset
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: 'bq'
#   timeout: 240s
#   args: ['mk', '${PROJECT_ID}:test_build']
  # env:
  # - 'CLOUDSDK_COMPUTE_REGION=us-central1'
  # - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'