substitutions:
  _FOLDER: "005__build-workflows"
  _WORKFLOW_NAME: "workflow"
  _BUCKET_NAME: "005__build-workflows"

steps:
# # Deploy workflow.yaml
# - name: 'gcr.io/cloud-builders/gcloud'
#   args:
#     - 'workflows'
#     - 'deploy'
#     - '${_WORKFLOW_NAME}'
#     - '--source'
#     - '${_FOLDER}/workflow.yaml'

# Copy required file to Cloud Storage
- name: 'gcr.io/cloud-builders/gsutil'
  args:
    - 'cp'
    - '${_FOLDER}/template/*'
    - 'gs://${_BUCKET_NAME}/template/'

# # Deploy Bigquery Statements
# - name: 'gcr.io/cloud-builders/gcloud'
#   entrypoint: 'bash'
#   args:
#     - '-c'
#     - |
#       cat ${_FOLDER}/database/*.sql | bq query --nouse_legacy_sql

# # Build Dataflow template
# - name: 'gcr.io/cloud-builders/python'
#   entrypoint: 'bash'
#   args:
#     - '-c'
#     - |
#       pip install --upgrade pip
#       pip install -r setup.py
#       python -m apache_beam.runners.interactive.interactive_beam --requirements_file=setup.py --runner DataflowRunner --job_name 005-build-workflow --template_location gs://${_BUCKET_NAME}/templates/wordcount-template

# Deploy Cloud Run Service
