options:
  # logging: cloud-logging-only
  logging: 'STACKDRIVER'
  # logsBucket: [NOMBRE_DE_TU_BUCKET]

substitutions:
  _FOLDER: "005__build-workflows"
  _WORKFLOW_NAME: "workflow"

steps:
- name: 'ubuntu'
  args: ["ls", "${_FOLDER}"]

# - name: 'gcr.io/cloud-builders/gcloud'
#   args:
#     # - 'beta'
#     - 'workflows'
#     - 'deploy'
#     - '${_WORKFLOW_NAME}'
#     - '--source'
#     - '${_FOLDER}/workflow.yaml'
    # - '--region'
    # - 'us-central1'
    # - '--replace'


# # create dataset
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: 'bq'
#   timeout: 240s
#   args: ['mk', '${PROJECT_ID}:test_build']
  # env:
  # - 'CLOUDSDK_COMPUTE_REGION=us-central1'
  # - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'