substitutions:
  _FOLDER: "005__build-workflows"
  _WORKFLOW_NAME: "workflow"
  _BUCKET_NAME: "005__build-workflows"

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'workflows'
    - 'deploy'
    - '${_WORKFLOW_NAME}'
    - '--source'
    - '${_FOLDER}/workflow.yaml'

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'gsutil'
    - 'ls'
    - 'gs://${_BUCKET_NAME}'
    # gs://${_BUCKET_NAME}/templates/wordcount-template

# - name: 'gcr.io/cloud-builders/python'
#   entrypoint: 'bash'
#   args:
#     - '-c'
#     - |
#       pip install --upgrade pip
#       pip install -r setup.py
#       python -m apache_beam.runners.interactive.interactive_beam --requirements_file=setup.py --runner DataflowRunner --job_name 005-build-workflow --template_location gs://${_BUCKET_NAME}/templates/wordcount-template


# # create dataset
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: 'bq'
#   timeout: 240s
#   args: ['mk', '${PROJECT_ID}:test_build']
  # env:
  # - 'CLOUDSDK_COMPUTE_REGION=us-central1'
  # - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'