substitutions:
  _FOLDER: "005__build-workflows"
  _WORKFLOW_NAME: "workflow"
  _BUCKET_NAME: "005__build-workflows"
  _PROJECT_ID: "fine-sublime-315119"
  _API_NAME: "build-workflow"

steps:
# # Deploy workflow.yaml
# - name: 'gcr.io/cloud-builders/gcloud'
#   args:
#     - 'workflows'
#     - 'deploy'
#     - '${_WORKFLOW_NAME}'
#     - '--source'
#     - '${_FOLDER}/workflow.yaml'

# # Copy required file to Cloud Storage
# - name: 'gcr.io/cloud-builders/gsutil'
#   args:
#     - 'cp'
#     - '${_FOLDER}/template/*'
#     - 'gs://${_BUCKET_NAME}/template/'

# # Deploy Bigquery Statements
# - name: 'gcr.io/cloud-builders/gcloud'
#   entrypoint: 'bash'
#   args:
#     - '-c'
#     - |
#       cat ${_FOLDER}/database/*.sql | bq query --nouse_legacy_sql

# Deploy Cloud Run Service
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/${_PROJECT_ID}/${_API_NAME}'
    - '${_FOLDER}/api/.'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'gcr.io/${_PROJECT_ID}/${_API_NAME}'

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - '${_API_NAME}'
    - '--image'
    - 'gcr.io/${_PROJECT_ID}/${_API_NAME}'
    - '--platform'
    - 'managed'
    - '--region'
    - 'us-central1'
