version: "3.8"

services:
  # Name of the service for handling templates
  templates:
    # Name of the container for the service
    container_name: dev_env_templates
    # Build the Docker image from Dockerfile in the current directory
    build: .
    # Command to keep the container running without performing specific tasks
    command: tail -f /dev/null
    volumes:
      # Map the current directory to /service inside the container
      - .:/service
