version: "3.8"

services:
  api:
    build: ./api/.
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
    env_file:
      - ./.env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google-credentials.json
